# Generated by Django 4.1.5 on 2023-02-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bet_tag',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='sport_tag',
            field=models.CharField(default='NFL', max_length=255),
            preserve_default=False,
        ),
    ]
